<?php

/* This file was generated by the 7_FixIconNameChanges upgrader */
$viewdefs['rt_client_reporting']['base']['menu']['header'] =  array (
  0 => 
  array (
    'route' => '#rt_client_reporting/create',
    'label' => 'LNK_NEW_RECORD',
    'acl_action' => 'create',
    'acl_module' => 'rt_client_reporting',
    'icon' => 'fa-plus',
  ),
  1 => 
  array (
    'route' => '#rt_client_reporting',
    'label' => 'LNK_LIST',
    'acl_action' => 'list',
    'acl_module' => 'rt_client_reporting',
    'icon' => 'fa-bars',
  ),
);
