<?php

/* This file was generated by the 7_FixIconNameChanges upgrader */
$viewdefs['mur_group_client_tasks']['base']['menu']['header'] =  array (
  0 => 
  array (
    'route' => '#mur_group_client_tasks/create',
    'label' => 'LNK_NEW_RECORD',
    'acl_action' => 'create',
    'acl_module' => 'mur_group_client_tasks',
    'icon' => 'fa-plus',
  ),
  1 => 
  array (
    'route' => '#mur_group_client_tasks',
    'label' => 'LNK_LIST',
    'acl_action' => 'list',
    'acl_module' => 'mur_group_client_tasks',
    'icon' => 'fa-bars',
  ),
);
