<?php
// WARNING: The contents of this file are auto-generated.

//Merged from custom/Extension/application/Ext/Include/ZuckerReports2.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['zr2_Report'] = 'zr2_Report';
$beanFiles['zr2_Report'] = 'modules/zr2_Report/zr2_Report.php';
$moduleList[] = 'zr2_Report';
$beanList['zr2_ReportContainer'] = 'zr2_ReportContainer';
$beanFiles['zr2_ReportContainer'] = 'modules/zr2_ReportContainer/zr2_ReportContainer.php';
$modules_exempt_from_availability_check['zr2_ReportContainer'] = 'zr2_ReportContainer';
$report_include_modules['zr2_ReportContainer'] = 'zr2_ReportContainer';
$modInvisList[] = 'zr2_ReportContainer';
$beanList['zr2_ReportParameter'] = 'zr2_ReportParameter';
$beanFiles['zr2_ReportParameter'] = 'modules/zr2_ReportParameter/zr2_ReportParameter.php';
$modules_exempt_from_availability_check['zr2_ReportParameter'] = 'zr2_ReportParameter';
$report_include_modules['zr2_ReportParameter'] = 'zr2_ReportParameter';
$modInvisList[] = 'zr2_ReportParameter';
$beanList['zr2_ReportParameterLink'] = 'zr2_ReportParameterLink';
$beanFiles['zr2_ReportParameterLink'] = 'modules/zr2_ReportParameterLink/zr2_ReportParameterLink.php';
$modules_exempt_from_availability_check['zr2_ReportParameterLink'] = 'zr2_ReportParameterLink';
$report_include_modules['zr2_ReportParameterLink'] = 'zr2_ReportParameterLink';
$modInvisList[] = 'zr2_ReportParameterLink';
$beanList['zr2_ReportTemplate'] = 'zr2_ReportTemplate';
$beanFiles['zr2_ReportTemplate'] = 'modules/zr2_ReportTemplate/zr2_ReportTemplate.php';
$modules_exempt_from_availability_check['zr2_ReportTemplate'] = 'zr2_ReportTemplate';
$report_include_modules['zr2_ReportTemplate'] = 'zr2_ReportTemplate';
$modInvisList[] = 'zr2_ReportTemplate';
$beanList['zr2_QueryTemplate'] = 'zr2_QueryTemplate';
$beanFiles['zr2_QueryTemplate'] = 'modules/zr2_QueryTemplate/zr2_QueryTemplate.php';
$modules_exempt_from_availability_check['zr2_QueryTemplate'] = 'zr2_QueryTemplate';
$report_include_modules['zr2_QueryTemplate'] = 'zr2_QueryTemplate';
$modInvisList[] = 'zr2_QueryTemplate';


//Merged from custom/Extension/application/Ext/Include/Client_List.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['cl_Client_list'] = 'cl_Client_list';
$beanFiles['cl_Client_list'] = 'modules/cl_Client_list/cl_Client_list.php';
$moduleList[] = 'cl_Client_list';


//Merged from custom/Extension/application/Ext/Include/upgrade_bwc.php
 
/* This file was generated by Sugar Upgrade */
$bwcModules[] = 'cl_Client_list';
$bwcModules[] = 'mur_approval_managment';
$bwcModules[] = 'mur_client_n_list';
$bwcModules[] = 'uc2ce_Click2Call';
$bwcModules[] = 'zr2_QueryTemplate';
$bwcModules[] = 'zr2_Report';
$bwcModules[] = 'zr2_ReportContainer';
$bwcModules[] = 'zr2_ReportParameter';
$bwcModules[] = 'zr2_ReportParameterLink';
$bwcModules[] = 'zr2_ReportTemplate';

$bwcModules[] = 'Leads';
//$bwcModules[] = 'zr2_ReportParameterLink';
//$bwcModules[] = 'zr2_ReportTemplate';


//Merged from custom/Extension/application/Ext/Include/msa.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['mur_msa'] = 'mur_msa';
$beanFiles['mur_msa'] = 'modules/mur_msa/mur_msa.php';
$moduleList[] = 'mur_msa';


//Merged from custom/Extension/application/Ext/Include/EmailTracker.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['mu_Enquriy_Tracker'] = 'mu_Enquriy_Tracker';
$beanFiles['mu_Enquriy_Tracker'] = 'modules/mu_Enquriy_Tracker/mu_Enquriy_Tracker.php';
$moduleList[] = 'mu_Enquriy_Tracker';


//Merged from custom/Extension/application/Ext/Include/approval_managment.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['mur_approval_managment'] = 'mur_approval_managment';
$beanFiles['mur_approval_managment'] = 'modules/mur_approval_managment/mur_approval_managment.php';
$moduleList[] = 'mur_approval_managment';


//Merged from custom/Extension/application/Ext/Include/client_new_list.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['mur_client_n_list'] = 'mur_client_n_list';
$beanFiles['mur_client_n_list'] = 'modules/mur_client_n_list/mur_client_n_list.php';
$moduleList[] = 'mur_client_n_list';


//Merged from custom/Extension/application/Ext/Include/tester.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['A1234_murano'] = 'A1234_murano';
$beanFiles['A1234_murano'] = 'modules/A1234_murano/A1234_murano.php';
$moduleList[] = 'A1234_murano';


//Merged from custom/Extension/application/Ext/Include/Universal_Click2Call.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['uc2ce_Click2Call'] = 'uc2ce_Click2Call';
$beanFiles['uc2ce_Click2Call'] = 'modules/uc2ce_Click2Call/uc2ce_Click2Call.php';
$modules_exempt_from_availability_check['uc2ce_Click2Call'] = 'uc2ce_Click2Call';
$modInvisList[] = 'uc2ce_Click2Call';


//Merged from custom/Extension/application/Ext/Include/Cosultants.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['mr_consultant'] = 'mr_consultant';
$beanFiles['mr_consultant'] = 'modules/mr_consultant/mr_consultant.php';
$moduleList[] = 'mr_consultant';


//Merged from custom/Extension/application/Ext/Include/Rebrand_Sugar.php
 
 //WARNING: The contents of this file are auto-generated


//Merged from custom/Extension/application/Ext/Include/group_client_tasks.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['mur_group_client_tasks'] = 'mur_group_client_tasks';
$beanFiles['mur_group_client_tasks'] = 'modules/mur_group_client_tasks/mur_group_client_tasks.php';
$moduleList[] = 'mur_group_client_tasks';


//Merged from custom/Extension/application/Ext/Include/Sorting.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['rt_sorting'] = 'rt_sorting';
$beanFiles['rt_sorting'] = 'modules/rt_sorting/rt_sorting.php';
$moduleList[] = 'rt_sorting';


//Merged from custom/Extension/application/Ext/Include/ClientReporting.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['rt_client_reporting'] = 'rt_client_reporting';
$beanFiles['rt_client_reporting'] = 'modules/rt_client_reporting/rt_client_reporting.php';
$modules_exempt_from_availability_check['rt_client_reporting'] = 'rt_client_reporting';
$report_include_modules['rt_client_reporting'] = 'rt_client_reporting';
$modInvisList[] = 'rt_client_reporting';


//Merged from custom/Extension/application/Ext/Include/ReportBoard.php
 
 //WARNING: The contents of this file are auto-generated
$beanList['rt_report_board'] = 'rt_report_board';
$beanFiles['rt_report_board'] = 'modules/rt_report_board/rt_report_board.php';
$moduleList[] = 'rt_report_board';

