<?php 
/* This file was generated by Sugar Upgrade */
$bwcModules[] = 'cl_Client_list';
$bwcModules[] = 'mur_approval_managment';
$bwcModules[] = 'mur_client_n_list';
$bwcModules[] = 'uc2ce_Click2Call';
$bwcModules[] = 'zr2_QueryTemplate';
$bwcModules[] = 'zr2_Report';
$bwcModules[] = 'zr2_ReportContainer';
$bwcModules[] = 'zr2_ReportParameter';
$bwcModules[] = 'zr2_ReportParameterLink';
$bwcModules[] = 'zr2_ReportTemplate';

$bwcModules[] = 'Leads';
//$bwcModules[] = 'zr2_ReportParameterLink';
//$bwcModules[] = 'zr2_ReportTemplate';

